### ISSUE TITLE
Staking Error: Transaction reverted: function selector was not recognized and there's no fallback function

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#163]
**Describe the bug**
It appears there is a non-blocking error in the terminal when initiating a staking transaction using the SSV Manager smart contract (before even confirming the transaction in Metamask).

**To Reproduce**
1. Run casimir using `npm run dev <--speculos>`
2. Click to connect Metamask
3. Fill in value you want to stake and click the Stake button
4. See error in the terminal

**Expected behavior**
There shouldn't be an error in the terminal.

**Screenshots**
Error in the terminal: <img width="1288" alt="image" src="https://user-images.githubusercontent.com/15663412/197238621-6d7f62ab-15a4-48c5-b194-abfb1e05f25f.png">

No error on the front-end or in the wallet:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15663412/197239100-0f1ebd52-1b93-446f-a7fb-e1649d323ab7.png">

**Additional context**
***CoinbaseWallet*** - Couldn't test it at the time.
***Ledger*** - Does not throw the issue.
***WalletConnect*** - Tried to test this as well, but it appears it has it's own bug that needs fixing...

**Comment by shanejearley** [comment]
Got it, thank you. Will look into it and report back.
