### ISSUE TITLE
Prototype connect, transfer and stake with Trezor provider

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#166]
It will be great to do a bit of background research and library comparison (issue searching) before starting this integration, just as you've done with the others. I took a peek at their emulator and will preemptively add the config script with a similar experience to our Ledger Speculos setup. We will probably also want to replicate the Ethers/Ledger Signer but for Ethers/Trezor, so I'll add some notes soon for you to take that on with this task.

**Comment by ccali11** [comment]
@shanejearley 🚀  (in response to the description).
