### ISSUE TITLE
Prototype single-account ROI with Athena

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#168]
If you take this on in parallel with #75 this should serve as a good way to get to the core of the first processor calculation and the aggregate table needs for ROI. The working code doesn't need to go into a formal Lambda API structure or version control yet (#75 and any crawler changes will need to come first anyways). 

First, we should try adding price data to each event in the crawler with the free [CoinGecko API](https://www.coingecko.com/en/api) (limited to 50 calls/minute, but we should only need to call it once for each block). Then in the processor prototype, start with something like this: select any `to_address` from the events table and query for all ETH transfers for that address, including the cost basis of the transfer (price times amount). Then you can use a Presto function to output single-account ROI:  

> ROI = (net return (sum of each _transfer out x price at transfer_) + current value (_current balance x current price_)) / net cost (sum of each _transfer in x price at transfer_)

*Sorry, GH markdown wasn't rendering math for this issue otherwise I would have written it clearer.

**Comment by elizyoung0011** [comment]
@hawyar @shanejearley 

I think we should update the fomula above slightly to be:

_ROI =( current value (current balance x current price) - net cost (sum of each transfer in x price at transfer) / net cost (sum of each transfer in x price at transfer))_

^^ We want to exclude net return for V1 as we cannot assume an asset leaving a connected wallet (a transfer out) is a return for the user, could be a transfer to an unconnected wallet, a payment, a gift etc. 

when you get into writing logic/calculation let me know, happy to help and would love to start playing with the data once we have wallets connected to see what the transactions look like and play with a few scenarios to make sure we're accounting for all cases, but currently storing some scenarios/ logic here:

https://docs.google.com/spreadsheets/d/1SB3Ch4hUE9jY7qplXGwBNHLoYxBLHAvpbgacwN-G2ec/edit#gid=1514521535

**Comment by shanejearley** [comment]
Thank you so much for the revision and scenarios @elizyoung0011 – with @hawyar's work so far I think we're about a week away from a time when you can sandbox these account scenarios all day long with the full Ethereum event with price dataset.

#168 will be a good issue to have you review when it's ready later this week.

**Comment by elizyoung0011** [comment]
Thanks @shanejearley !! Once we sandbox these accounts, there is chance we can add back in net return from sold rewards to the ROI calculation (that will be a more complete picture -essentially how a return on a stock investment account is calculated), but hard to say if that will be reasonable for V1 given we are unlikely to have the full purchase history.

**Comment by shanejearley** [comment]
That sounds like an excellent plan. Also, what a day – didn't realize I was linking to this issue inside of this issue.
