### ISSUE TITLE
Prototype view, save, transfer and stake wallet integrations

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#19]

**Comment by shanejearley** [comment]
Prototype UI-agnostic wallet integrations – since we are still designing that user experience – (on a testnet network) in a [Casimir](https://github.com/consensusnetworks/casimir) test branch for viewing an account balance, saving accounts between sessions (cache or otherwise with easy destroy methods @ccali11 
- [ ] Prototype lookup and save account with WalletConnect provider
- [ ] Prototype lookup and save account with Metamask provider
- [ ] Prototype account and network switching (including between wallet providers and ETH testnets)

Finally, we'll test a some transactions with the current selected account @ccali11 
- [ ] Prototype a transfer to another wallet
- [ ] Prototype a simple stake to an existing contract using ABI

We can start with the view and save aspect. Once we are set up to switch between accounts (across these various wallet providers below), we can set up a the transfer and stake transactions with [ethersjs](https://docs.ethers.io/v5/) (the smaller, less-buggy Ethereum browser lib). I'll hunt down and save a simplified contract to [Ethereum Stack](https://github.com/consensusnetworks/ethereum-stack) (and pass along an ABI for you to pull in)  @ccali11 
- [ ] Prototype contract ABI workflow with app (using existing simple contract) between [Casimir](https://github.com/consensusnetworks/casimir) and [Ethereum Stack](https://github.com/consensusnetworks/ethereum-stack)

**Comment by ccali11** [comment]
Notes from review with Shane 
- Create a separate page for all wallet interactions (create a new directory within `pages` directory called `wallet` with one file called `wallet.vue`)
- Chris review more and test hypothesis that you can't switch between accounts within provider in window (user needs to use browser extension)
- Next, try implementing provider switching within window (start with Coinbase Wallet or WalletConnect)

**Comment by shanejearley** [comment]
> 



> Notes from review with Shane
> 
> * Create a separate page for all wallet interactions (create a new directory within `pages` directory called `wallet` with one file called `wallet.vue`)
> * Chris review more and test hypothesis that you can't switch between accounts within provider in window (user needs to use browser extension)
> * Next, try implementing provider switching within window (start with Coinbase Wallet or WalletConnect)
> * Define html elements in global namespace using refs (see Shane's recent PR Chris reviewed for syntax)
> * Define etheruem window object for typescript (set `lang="ts"` within `<script setup>`) and / or declare ethereum object in  global namespace

Latest commit resolves this last bullet^
