### ISSUE TITLE
Trezor staking requires too many signatures

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#194]
**Describe the bug**
Current Trezor Wallet integration requires two signatures before signing final transaction (3rd signature) (plus an additional one to connect the wallet in the first place). Ideally there would only be two signatures at the most (one to connect, and one to sign the transaction).

**To Reproduce**
1. Run the Casimir application `npm run dev --ledger --trezor`
2. Start the Trezor bridge (`http://localhost:9002`) and load seed phrase
3. Click on "Connect Trezor" button
4. Follow the prompts to export your address any time a new (Trezor-driven) browser tab opens
5. Repeat until you achieve a successful transaction or stake

**Expected behavior**
Ideally there would only be two signatures at the most (one to connect, and one to sign the transaction).

**Screenshots**
(above description should suffice)

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey 12.3.1
 - Browser: Chrome

**Additional context**
None.

**Comment by shanejearley** [comment]
Will make getting rid of this weird behavior a part of adding Bitcoin integration with Trezor.
