### ISSUE TITLE
Query Casimir/SSV fees from the Manager contract and add to stake action

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#199]
Adding this to the wallet composable work. These are protocol fees that we need to 1) show users before they deposit so they know their total (deposit + fees) and the breakdown. I will tag you in the PR that adds these methods to the contract, where I also have a test showing usage.

**Comment by ccali11** [comment]
@shanejearley - Sweet. Sounds good. May have a question about this at our standup later.
