### ISSUE TITLE
Add IoTeX delegate selection and staking support

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#228]
See the staking interfaces for the stake action methods: https://github.com/iotexproject/iotex-antenna/blob/53fa957949bb8de43d604f86dd8ff7ba3d40721f/src/rpc-method/types.ts#L399

We can fetch the initial list of delegates from their (IoTeX) analytics endpoints. Select one and use the name as input to create stake action. Then interact with the stake bucket that is created (deposit, withdraw, transfer).

**Comment by ccali11** [comment]
Discussed with @shanejearley the current limitations of implementing this as noted in [this discussion](https://github.com/consensusnetworks/casimir/discussions/100#discussioncomment-4783233). Will revisit when I hear more from IoTeX team and may play around with a few methods that aren't yet well documented for this purpose in the meantime.

**Comment by ccali11** [comment]
Closing as not planned.
