### ISSUE TITLE
Publish transfer events with the performance-optimized version of the crawler

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#229]
Keep us posted on your findings here as well! Finishing this should result in a full events dataset synced in Athena with realtime updates from the crawler stream.

**Comment by shanejearley** [comment]
How is the PR going for this one?

**Comment by hawyar** [comment]
Publishing transfers is ongoing and seems well. The improvement mentioned here is included in the roi PR https://github.com/consensusnetworks/casimir/pull/193. We can close this once the other is finished.
