### ISSUE TITLE
Fix Coinbase Wallet connection and network switching

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#246]
### Coinbase Wallet Update

Noticing a few things to look into:
- [x] Wallet doesn't appear to be connected to Casimir (dapp) based on interface. Fix this.
- [ ] Wallet doesn't appear to support importing addresses (such as an IoTeX address). It may not even support this chain/token.
- [ ] Switching network to IoTeX network doesn't seem to throw an error, but chain does not switch.

_Originally posted by @ccali11 in https://github.com/consensusnetworks/casimir/discussions/100#discussioncomment-4783272_

**Comment by shanejearley** [comment]
Is this backlogged?

**Comment by shanejearley** [comment]
We should circle back to some testing here – the issues we had on our local network yesterday seemed fixable, but also only important for the local network.
