### ISSUE TITLE
Add complete mock data to user composable

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#252]
@chris continuing the logic from [here](https://github.com/consensusnetworks/casimir/issues/198) (the bottom posts about users and accounts - please read and check out the User, Account, and other TS definitions). You care about creating a method to get the current user's data (still mock data for now). You should get everything you need back from one call (later we'll add a subscription to receive updates):
```ts

/** Fetch Casimir users */

const user: User = {
  address: '0x123...'
  accounts: [
    {
      address: '0x123...'
      currency: 'ETH',
      balance: '1000000...',
      balanceSnapshots: [{ date: '2023-02-06', balance: '1000000' }, { date: '2023-02-05, balance: '1000000' }/** ... up to 100 days ago */],
      roi: 0.25,
      walletProvider: 'MetaMask'
    },
    {
      address: '0x456...'
      currency: 'ETH',
      balance: '1000000...',
      balanceSnapshots: [{ date: '2023-02-06', balance: '1000000' }, { date: '2023-02-05, balance: '1000000' }/** ... up to 100 days ago */],
      roi: 0.25,
      walletProvider: 'MetaMask'
    }
  ]
}
```

You could make some mock data to match the pre-known addresses we are using in our local fork with the shared seed. Also, we can keep fetching user pool data like we are in the wallet.ts (maybe move it to the same method as this in users.ts) but we will eventually just send this data back from the user fetch as mentioned in Hawyar's issue. I'm also ignoring rewards and stake but those can be summed from pools. (I will also make updates to the contract to provide things like claimed rewards vs. available rewards for Steve's needs, so feel free to assume you have any of these things for now and just keep note.) 

So using the mock data approach (seems like one whole user is enough, with an account for each of the wallets you have connected), export methods for the remainder of Steve's (improvised) login flow and portfolio/staking pages. We'll use that feedback to tweak things on the backend and then tie things together later in the week. 

If you can, let's also ignore the real-time aspect for now (and discuss it later this week), and just reduce the flow down to:
1. User signs up
2. Add the user to users (get the user from your simple mock data)
3. Expose in composable method for components

The final query itself will be something like a PG SQL join of the user to accounts (on the user's primary address). The data will get there in this order: 
1. User signs up 
2. Add the user to users (which triggers BE to add the user's primary account to accounts) and subscribe to the user
3. New on-chain blocks trigger the processor to calculate updated metrics for all accounts (#198)
4. Receive an update from the user subscription with the user's updated accounts data
5. Expose in composable method for components

I've noticed some small things missing from the example types I provided so definitely scrutinize it.

**Comment by shanejearley** [comment]
@hawyar just making sure you see this for context.

**Comment by shanejearley** [comment]
Any update here?

**Comment by ccali11** [comment]
Yes. This is all embedded in my most recent PR.

**Comment by ccali11** [comment]
This is OBE (overcome by events) with all of the data architecture / schema work we've done over the past several weeks. 👍
