### ISSUE TITLE
Add user sessions

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#255]
About to add more requirement details and direction to this issue.

**Comment by shanejearley** [comment]
A meeting will probably also be helpful at that point.

**Comment by shanejearley** [comment]
@ccali11 Ok, so the goal in this issue should be to integrate the [SuperTokens sessions recipe](https://supertokens.com/docs/session/introduction) with the current wallet signature verification. We should be able to log in with the wallet verification, then fetch user data (in a separate call to the server) with the verified session, and then log out. As I mentioned, you've got the code in a good place to make this a relatively smooth task. Theirs seems like an excellent product as well.

While doing some diligence on using SuperTokens, I put together [this sample repo code](https://github.com/consensusnetworks/supertokens-test) which documents a standard integration with the sessions recipe. I used userAddress instead of userId, but otherwise, I omitted any wallet code on FE or BE. If you clone it and npm run dev, click around, then work through comments in the code flow from login to logout. 

You'll also note that we're using their testing core server in our backend config, which will be totally fine for your development next week – in the meantime I'll return back to infrastructure/ops and add our own deployment of their core server components – plus any scripts/environment variables to handle prod/dev stages and local work.

**Comment by shanejearley** [comment]
Lastly, a less critical point regarding the express service name `auth`. We'll change it to the more accurate name `users` in a small PR somewhere. Auth components will be deployed (SuperTokens core and session DB) but the auth business logic is minimal enough that we can stick that in the same service dedicated to calling our separate `users` DB. We can eventually break out the auth config and validation logic into a dedicated service, but probably not until end-users have a need to call another service endpoint in our backend besides `users` (and handle it like [this](https://supertokens.com/docs/session/common-customizations/sessions/multiple-api-endpoints)).

**Comment by shanejearley** [comment]
@ccali11 you don't need to review every inch of the PR but I did make those changes mentioned above in #260 if you want to note and provide approval.

**Comment by ccali11** [comment]
Sweet. Started taking a look at this. Going to dive in tomorrow.
