### ISSUE TITLE
MetaMask-SSV Staking Bug: `Error: Transaction reverted: function selector was not recognized and there's no fallback function`

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#279]
**Describe the bug**
When staking with MetaMask, an error is thrown on our server indicating that the transaction reverted due to an "unrecognized function selector" in the SSV smart contract. This is a non-blocking error. The MetaMask wallet interface shows the confirmed transaction, querying the smart contract for user pools returns expected values, and it works just fine with Ledger wallet. I've tried commenting out the mining interval as well as overriding the transaction type using `type: 0`, but the error still throws in both cases.

**To Reproduce**
1. Launch the app
2. Connect MetaMask
3. Indicate how much you'd like to stake
4. Click stake
5. Note the server error
6. Click on button to see user pools / balances (query smart contract)
7. Connect ledger
8. Repeat staking process
9. Note absence of error in server

**Expected behavior**
We should see the staking transaction occur in the server without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/15663412/223242182-390b4012-e7d9-4291-b3a7-1c0aaf13cb25.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Brave

**Comment by shanejearley** [comment]
Can probably close this. I think it was interface related. You'll also see unrecognized selector in the current logs when calling an external contract that we aren't compiling (completely fine to ignore in this case).
