### ISSUE TITLE
CoinbaseWallet sometimes opens when attempting to connect to MetaMask

### ISSUE THREAD

**Issue by ccali11** [consensusnetworks/casimir#281]
**Describe the bug**
CoinbaseWallet sometimes opens when attempting to connect to MetaMask

**To Reproduce**
1. Launch App
2. Click to connect MetaMask wallet
3. CoinbaseWallet sometimes pops up instead

**Expected behavior**
Only MetaMask should pop up every time.

**Comment by Angelsnevercry** [comment]
@ccali11 We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/

**Comment by ccali11** [comment]
It appears that this has been incidentally resolved by refactors and code improvements because I can no longer replicate this bug in `develop`.

**Comment by ccali11** [comment]
Reopening as I've seen the issue pop up again (on our site and on Lido's staking site) AND I've encountered a UX solution per the [MetaMask docs](https://docs.metamask.io/guide/accessing-accounts.html)

**Comment by ccali11** [comment]
I decoupled some logic and this again seems to be resolved. Closing again for now. 👍
