### ISSUE TITLE
Finalize tabs, views, labels, and tooltips

### ISSUE THREAD

**Issue by elizyoung0011** [consensusnetworks/casimir#384]
Can we remove unused text/ additional page links  

![image](https://github.com/consensusnetworks/casimir/assets/10892339/460311bd-6707-4de6-8954-fc448897f049)

And add tooltips : where we need them and text here: https://docs.google.com/document/d/1Dz1XNQswknjnA8mC43VZo33uQ180swzewCIPlMvibV0/edit?pli=1

If working on anything for operators page, this can be done after that. 
Thanks!!

**Comment by shanejearley** [comment]
@elizyoung0011 keeping open and broadened to finalizing some views/tabs/wording/etc. for the frontend.

**Comment by elizyoung0011** [comment]
@DemogorGod one more requirement for graph at the top. 

We would like the graph to show time series data of the three top line metrics:
- wallet balance
- current stake
- all time staking rewards 

Notes below.  If it will slow down goerli launch to have all 3 metrics (lines) on the graph, we can launch with simply just wallet balance and then add the other 2 later. 

Thanks! 

<img width="1108" alt="image" src="https://github.com/consensusnetworks/casimir/assets/10892339/faf03b73-a155-4d37-8542-a5429167d945">

**Comment by DemogorGod** [comment]
@elizyoung0011 

I have some concerns with adding some of those metrics on the same graph. 

Adding the total balance is a great idea and is doable. 

However, adding the currently staked and total rewards might confuse the user on the line. It will also crowd the graph. 

I suggest doing it in either tabs or creating a new component that shows those items. (Perhaps leave those metrics for the staking page that will be created in the future)

**Comment by elizyoung0011** [comment]
@DemogorGod that is fine to begin with just wallet balance for now then. Idea with showing  all 3is to hopefully be able see rewards growing over time and also give user idea of how much of their eth is staked relative to their total holding, but agree could also be done in separate tabs or in a more detailed page so can hold off for now. 

Thanks!

**Comment by elizyoung0011** [comment]
@DemogorGod Shane and Nate agreed we do want to show all three values on the graph (as three separate lines). Happy to discuss best of way to doing this. Could have a toggle for user to select which metrics (lines) they want shown and we may want a dual axis and to put staking and rewards value on the second axis as the scale of those 2 metrics will probably be a lot smaller than wallet balance.

**Comment by elizyoung0011** [comment]
@DemogorGod more detailed reqs for the graph here: Thanks!!

https://www.figma.com/file/5P1IAw6FQO8cnQiaAntS9W/Main-page-graph-Reqs?type=whiteboard&node-id=101-24&t=y4HdfsgRKRzogJui-0
