### ISSUE TITLE
<undefined> text in place of unit on top line values on staking main page 

### ISSUE THREAD

**Issue by elizyoung0011** [consensusnetworks/casimir#452]
for the top line values - undefined was showing up after value

<img width="1207" alt="image" src="https://github.com/consensusnetworks/casimir/assets/10892339/410f05db-b957-46cc-ae07-ab917fe35dcb">

<img width="1143" alt="image" src="https://github.com/consensusnetworks/casimir/assets/10892339/e80a30a4-4f99-4c1e-ab6d-d80cd4c90c9c">

**Comment by ccali11** [comment]
I will take a look

**Comment by ccali11** [comment]
Fixed this last week in #455

**Comment by ccali11** [comment]
Fixed this last week in https://github.com/consensusnetworks/casimir/pull/455
